language: c

env:
  matrix:
    - EVM_EMACS=emacs-24.5-travis
    - EVM_EMACS=emacs-25.2-travis
    - EVM_EMACS=emacs-26.1-travis

before_install:
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH=$HOME/.evm/bin:$PATH
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip

install:
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH=/home/travis/.cask/bin:$PATH
  - cask install

script:
  - cask exec ert-runner

notifications:
  email: false
